
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

 
public class ResultsGUI extends javax.swing.JFrame {

    /**
     * Creates new form SavedAds
     */
        private static String  SC;
    private static String  ZC;
    private static Double  RD;
    DefaultTableModel model;
    private static Connection conn=DatabaseConnect.ConnerDb();
    ResultSet rs=null;
    PreparedStatement pst=null;
    public ResultsGUI() {
        initComponents();
        Update_table();
     setDefaultCloseOperation(EXIT_ON_CLOSE);   
    }
     private void Update_table(){
   ResultsTable.setModel(new javax.swing.table.DefaultTableModel(
           SearchAPP.table,
            new String [] {
                "Ad Tittle", "Location", "Time Posted", "Ad Type", "URL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
           TablePanel.setViewportView(ResultsTable);
        if (ResultsTable.getColumnModel().getColumnCount() > 0) {
            ResultsTable.getColumnModel().getColumn(0).setMinWidth(200);
            ResultsTable.getColumnModel().getColumn(0).setPreferredWidth(250);
            ResultsTable.getColumnModel().getColumn(0).setMaxWidth(600);
            ResultsTable.getColumnModel().getColumn(1).setMinWidth(50);
            ResultsTable.getColumnModel().getColumn(1).setPreferredWidth(75);
            ResultsTable.getColumnModel().getColumn(1).setMaxWidth(150);
            ResultsTable.getColumnModel().getColumn(2).setMinWidth(50);
            ResultsTable.getColumnModel().getColumn(2).setPreferredWidth(75);
            ResultsTable.getColumnModel().getColumn(2).setMaxWidth(150);
            ResultsTable.getColumnModel().getColumn(3).setMinWidth(75);
            ResultsTable.getColumnModel().getColumn(3).setPreferredWidth(100);
            ResultsTable.getColumnModel().getColumn(3).setMaxWidth(200);
            ResultsTable.getColumnModel().getColumn(4).setMinWidth(20);
            ResultsTable.getColumnModel().getColumn(4).setPreferredWidth(25);
            ResultsTable.getColumnModel().getColumn(4).setMaxWidth(600);
        }
    //    ResultsTable.setAutoCreateRowSorter(true); 
         
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchPanel = new javax.swing.JPanel();
        SC1 = new javax.swing.JTextField();
        RD1 = new javax.swing.JTextField();
        ZC1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Search = new javax.swing.JButton();
        HeaderLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ResultsPanel = new javax.swing.JPanel();
        TablePanel = new javax.swing.JScrollPane();
        ResultsTable = new javax.swing.JTable();
        HeaderPanel = new javax.swing.JPanel();
        ViewOnline = new javax.swing.JButton();
        ManageAds = new javax.swing.JButton();
        SaveAds = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        header = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Results");

        SearchPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        SC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SC1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Mincho Light", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText(" Radius(km)");

        jLabel4.setFont(new java.awt.Font("Yu Mincho Light", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText(" Search Content");

        jLabel2.setFont(new java.awt.Font("Yu Mincho Light", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("   Zip Code");

        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        HeaderLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/craigslistdealers1.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/craigslistdealers2.png"))); // NOI18N

        javax.swing.GroupLayout SearchPanelLayout = new javax.swing.GroupLayout(SearchPanel);
        SearchPanel.setLayout(SearchPanelLayout);
        SearchPanelLayout.setHorizontalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(HeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(SearchPanelLayout.createSequentialGroup()
                        .addComponent(SC1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(SearchPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)))
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ZC1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RD1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Search)
                .addContainerGap())
        );
        SearchPanelLayout.setVerticalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SC1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ZC1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RD1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(HeaderLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ResultsPanel.setToolTipText("Results");
        ResultsPanel.setLayout(null);

        TablePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ResultsTable.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));
        ResultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ad Tittle", "Location", "Time Posted", "Ad Type", "URL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ResultsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResultsTableMouseClicked(evt);
            }
        });
        TablePanel.setViewportView(ResultsTable);
        if (ResultsTable.getColumnModel().getColumnCount() > 0) {
            ResultsTable.getColumnModel().getColumn(0).setMinWidth(200);
            ResultsTable.getColumnModel().getColumn(0).setPreferredWidth(250);
            ResultsTable.getColumnModel().getColumn(0).setMaxWidth(600);
            ResultsTable.getColumnModel().getColumn(1).setMinWidth(50);
            ResultsTable.getColumnModel().getColumn(1).setPreferredWidth(75);
            ResultsTable.getColumnModel().getColumn(1).setMaxWidth(150);
            ResultsTable.getColumnModel().getColumn(2).setMinWidth(50);
            ResultsTable.getColumnModel().getColumn(2).setPreferredWidth(75);
            ResultsTable.getColumnModel().getColumn(2).setMaxWidth(150);
            ResultsTable.getColumnModel().getColumn(3).setMinWidth(75);
            ResultsTable.getColumnModel().getColumn(3).setPreferredWidth(100);
            ResultsTable.getColumnModel().getColumn(3).setMaxWidth(200);
            ResultsTable.getColumnModel().getColumn(4).setMinWidth(20);
            ResultsTable.getColumnModel().getColumn(4).setPreferredWidth(25);
            ResultsTable.getColumnModel().getColumn(4).setMaxWidth(600);
        }

        HeaderPanel.setLayout(null);

        ViewOnline.setText("View Selected Ad");
        ViewOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewOnlineActionPerformed(evt);
            }
        });
        HeaderPanel.add(ViewOnline);
        ViewOnline.setBounds(20, 20, 140, 23);

        ManageAds.setText("Manage Save Ads");
        ManageAds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageAdsActionPerformed(evt);
            }
        });
        HeaderPanel.add(ManageAds);
        ManageAds.setBounds(420, 20, 140, 23);

        SaveAds.setText("Save Selected Ad");
        SaveAds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAdsActionPerformed(evt);
            }
        });
        HeaderPanel.add(SaveAds);
        SaveAds.setBounds(220, 20, 140, 23);

        refresh.setText("Refresh Results");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        HeaderPanel.add(refresh);
        refresh.setBounds(610, 20, 130, 23);

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Purple-header2.jpg"))); // NOI18N
        HeaderPanel.add(header);
        header.setBounds(0, 0, 760, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TablePanel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ResultsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 31, Short.MAX_VALUE)
                        .addComponent(ResultsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
        );

        setSize(new java.awt.Dimension(781, 578));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SC1ActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
                 SearchAPP.Results.clear();
                 SearchAPP.URL.clear();
                 SearchAPP.count=-1;
                 SearchAPP.done=0;
                 SearchAPP.table=null;
            try {
   
     SC=SC1.getText();
           ZC=ZC1.getText();        
           RD = Double.parseDouble(RD1.getText());
          
                      SearchAPP.SearchFunction(SC, ZC, RD); 
           SearchAPP.table = new Object [100*SearchAPP.URL.size()][5];
           System.out.println(SearchAPP.table.length);
         for (int i = 0; i <SearchAPP.Results.size();i++)  //99*SearchAPP.URL.size()               
           new Thread(new SearchAPP.ST()).start(); 
           JOptionPane.showMessageDialog(null, "Searching!!!! please wait couple seconds "); 
           int process=0;
           while(SearchAPP.done<SearchAPP.Results.size()){
             System.out.println("Processing %"+SearchAPP.done);
          
             if(SearchAPP.count>SearchAPP.done+100)
             {
                 JOptionPane.showMessageDialog(null,"Your Internet is really slow!  Some contents may be missing.Click Refresh bottom to view Missing part OR TRY it later.");
                 break;
             }
            // jProgressBar1.setValue(SearchAPP.done);
         }
              Update_table();
             }catch(Exception e){
               JOptionPane.showMessageDialog(null, "No Results found, Please recheck the query"); 
           }
       

           
           
    }//GEN-LAST:event_SearchActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        Update_table(); 
        
             // TODO add your handling code here:
    }//GEN-LAST:event_refreshActionPerformed

    private void ManageAdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageAdsActionPerformed
        dispose();
        AdsManagementGUI AM = new AdsManagementGUI();
        AM.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_ManageAdsActionPerformed

    private void ViewOnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewOnlineActionPerformed
                         try {
                            int row = ResultsTable.getSelectedRow();
                            String Table_click=(ResultsTable.getModel().getValueAt(row,4).toString());
                        String[] cmd = new String[4];
                        cmd[0] = "cmd.exe";
                        cmd[1] = "/C";
                        cmd[2] = "start";
                        cmd[3] = Table_click;
                         Process p = Runtime.getRuntime().exec(cmd);
        }catch(Exception e){
               JOptionPane.showMessageDialog(null, "error"); 
           }
    }//GEN-LAST:event_ViewOnlineActionPerformed

    private void ResultsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResultsTableMouseClicked
            // TODO add your handling code here:
    }//GEN-LAST:event_ResultsTableMouseClicked

    private void SaveAdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAdsActionPerformed
         try {
                            int row = ResultsTable.getSelectedRow();
                            String ad_tittle=(ResultsTable.getModel().getValueAt(row,0).toString());
                            String location=(ResultsTable.getModel().getValueAt(row,1).toString());
                            String time_posted=(ResultsTable.getModel().getValueAt(row,2).toString());
                            String ad_type=(ResultsTable.getModel().getValueAt(row,3).toString());
                            String ad_url=(ResultsTable.getModel().getValueAt(row,4).toString());
                            System.out.println(ad_tittle);
                            System.out.println(location);
                            System.out.println(time_posted);
                            System.out.println(ad_type);
                            System.out.println(ad_url);
           String SQL="INSERT INTO `database`.`sr` (`ad_tittle`, `location`, `time_posted`, `ad_type`, `ad_url`) VALUES ('"+ad_tittle+"', '"+location+"', '"+time_posted+"', '"+ad_type+"', '"+ad_url+"');";
           pst = conn.prepareStatement(SQL);       
           pst.execute();
           JOptionPane.showMessageDialog(null, "saved"); 
        }catch(Exception e){
               JOptionPane.showMessageDialog(null, "error"); 
           }// TODO add yo           // TODO add your handling code here:
    }//GEN-LAST:event_SaveAdsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HeaderLabel;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JButton ManageAds;
    private javax.swing.JTextField RD1;
    private javax.swing.JPanel ResultsPanel;
    private javax.swing.JTable ResultsTable;
    private javax.swing.JTextField SC1;
    private javax.swing.JButton SaveAds;
    private javax.swing.JButton Search;
    private javax.swing.JPanel SearchPanel;
    private javax.swing.JScrollPane TablePanel;
    private javax.swing.JButton ViewOnline;
    private javax.swing.JTextField ZC1;
    private javax.swing.JLabel header;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton refresh;
    // End of variables declaration//GEN-END:variables
}
