/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.io.BufferedReader;
import java.io.File;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;



/**
 *
 * @author Qiang
 */
public class SearchGUI extends javax.swing.JFrame {
    private static Connection conn=DatabaseConnect.ConnerDb();
    private static ResultSet rs=null;
    private static PreparedStatement pst=null;
    //private static Timer t=null;
    private static String  SC;
    private static String  ZC;
    private static Double  RD;

   // public static int loadingMore=0;
   // int count=0;
    /**
     * Creates new form DriverApp
     */
    public SearchGUI() {
        new File("C:\\Craigslist").mkdirs();
        if(!CheckDataBase())
        importData();
        initComponents();
        
        /*t = new Timer(1000, new ActionListener(){
               
               public void actionPerformed(ActionEvent e){
                  count++;
                   SearchingProgress.setValue(count);
                 if(SearchingProgress.getValue()<100)
                  SearchingProgress.setValue(SearchingProgress.getValue()+1);
                  System.out.println(count);
               }              
           });
           t.start();*/
        setResizable(false);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }
    public void importData(){
        
              loadSQL("database_sr.sql");
              loadSQL("database_clist.sql");       
              loadSQL("database_zip.sql");
    }
    public static boolean CheckDataBase(){
        boolean  Exists=false;
    try{
         String query = "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='database'";
        Statement st = conn.createStatement(); 
        ResultSet rs = st.executeQuery(query);                  
        rs.next();
         Exists = rs.getInt("COUNT(*)") > 0;
    }catch(Exception e){
        
        JOptionPane.showMessageDialog(null, "Failure");
    }
        
        return Exists;
        
    }
    public  void loadSQL( String FileName) {
         try {
             
             //File file = new File("src\\DATA\\"+FileName);
             String path ="/DATA/"+FileName;
             InputStream is=this.getClass().getResourceAsStream(path);
             BufferedReader reader = new BufferedReader(new InputStreamReader(is));
             StringBuilder sb = new StringBuilder();
             String line = reader.readLine();
             while(line!=null){
                     sb.append(line);
                   //  System.out.println(sb.toString());
                 line = reader.readLine();
                 
             }
             String[] inst = sb.toString().split(";");
                        Connection conn=DatabaseConnect.ConnerDb();
                        Statement st = conn.createStatement();      
                 for (int i = 0; i < inst.length; i++) {
                     System.out.println(inst[i]);
                if (!inst[i].trim().equals("")) {
                    st.executeUpdate(inst[i]);
                    System.out.println(">>" + inst[i]);
                }
            }
                 JOptionPane.showMessageDialog(null,"Loaded Compleat");
      
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SC1 = new javax.swing.JTextField();
        SearchBottom = new javax.swing.JButton();
        ZC1 = new javax.swing.JTextField();
        RD1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        SearchBottom.setFont(new java.awt.Font("Segoe UI Semibold", 1, 11)); // NOI18N
        SearchBottom.setText("Search");
        SearchBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBottomActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Mincho Light", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("    Zip Code");

        jLabel3.setFont(new java.awt.Font("Yu Mincho Light", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("   Radius(km)");

        jLabel4.setFont(new java.awt.Font("Yu Mincho Light", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("                                            Search Content");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SC1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(ZC1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RD1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchBottom)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(RD1))
                    .addComponent(SC1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ZC1)
                    .addComponent(SearchBottom, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/craigslistdealers.png"))); // NOI18N

        jLabel5.setText("Coding by Qiang Dong");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182))))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(758, 251));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SearchBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBottomActionPerformed
 try{     
            
             
          SC=SC1.getText();
           ZC=ZC1.getText();        
           RD = Double.parseDouble(RD1.getText());
          
           SearchAPP.SearchFunction(SC, ZC, RD); 
           SearchAPP.table = new Object [100*SearchAPP.URL.size()][5];
           System.out.println(SearchAPP.table.length);
           
         for (int i = 0; i <SearchAPP.Results.size();i++)  //99*SearchAPP.URL.size()               
           new Thread(new SearchAPP.ST()).start(); 
           JOptionPane.showMessageDialog(null, "Searching!! please wait couple seconds !");  
           int process=0;
          while(SearchAPP.done<SearchAPP.Results.size()){
              System.out.println("Processing %"+SearchAPP.done); 
             if(SearchAPP.count>SearchAPP.done+100)
             {
                 JOptionPane.showMessageDialog(null,"Your Internet is really slow!  Some contents may be missing.Click Refresh bottom to view Missing part OR TRY it later.");
                 break;
             }
            // jProgressBar1.setValue(SearchAPP.done);
         }
        //  SearchAPP.SaveItintoTable();
          dispose();
         ResultsGUI sr = new ResultsGUI();
         sr.setVisible(true);   
         
           }catch(Exception e){
               JOptionPane.showMessageDialog(null, "No results, make sure you enter a valid query"); 
           }      

    }//GEN-LAST:event_SearchBottomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RD1;
    private javax.swing.JTextField SC1;
    private javax.swing.JButton SearchBottom;
    private javax.swing.JTextField ZC1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
